# Generated by Django 4.2.10 on 2024-03-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0003_product_is_sale_product_on_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=False, null=True, upload_to='uploads/products'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
