# Generated by Django 4.2.10 on 2024-03-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='on_discount',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploads/product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
