# Generated by Django 4.2.10 on 2024-03-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_discount',
            field=models.BooleanField(default=True),
        ),
    ]
