# Generated by Django 4.2.10 on 2024-02-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_product_on_discount_alter_product_is_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='discount_price',
        ),
    ]
