# Generated by Django 4.2.10 on 2024-02-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_rename_sale_price_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='uploads/product/'),
        ),
    ]
