# Generated by Django 4.2.10 on 2024-03-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_product_is_sale_alter_product_on_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
